### ISSUE TITLE
PyChrono on macOS failing to import

### ISSUE THREAD

**Issue by SoWizard** [projectchrono/chrono#306]
I'm trying to setup a new project with PyChrono on macOS 11.2.3 (macOS).

PyCharm is our preferred IDE so setting up a new Conda environment through there and then running `conda install -c projectchrono pychrono` results in failure - but let's leave that out of scope for this issue. My guess is that the Anaconda environment created in PyCharm forces Python 3.8 but PyChrono requires 3.7.

I also tried compiling Chrono through CMake. Compilation was successful and examples run (relatively) well, but ran into a problem when trying to import PyChrono into Python (v3.9 was installed, although I also tried it with 3.8 and got the same result). Likewise, let's leave it out of scope.

Reverting to doing everything through the command line (zsh) and setting up a brand new Conda environment allowed me to install PyChrono successfully through `conda install -c projectchrono pychrono`. I did realise it downgraded Python from 3.8.5 to 3.7.10. Now when I try to `import pychrono as chrono`, I get:

```
Python 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pychrono as chrono
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/opt/anaconda3/envs/ChronoEnv/lib/python3.7/site-packages/pychrono/__init__.py", line 44, in <module>
    from .core import *
  File "/Users/user/opt/anaconda3/envs/ChronoEnv/lib/python3.7/site-packages/pychrono/core.py", line 13, in <module>
    from . import _core
ImportError: dlopen(/Users/user/opt/anaconda3/envs/ChronoEnv/lib/python3.7/site-packages/pychrono/_core.so, 2): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/user/opt/anaconda3/envs/ChronoEnv/lib/python3.7/site-packages/pychrono/_core.so
  Reason: image not found

```

I have a feeling this might be an issue with different Python versions but can't quite figure it out. Any help here would be hot.

**Comment by SoWizard** [comment]
Nevermind, I've been butting my head against this for hours before landing here and didn't read the error properly this time around 🥲.

`Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib` is the culprit.

Installed libomp through brew (`brew install libomp`) worked like a charm.

I do believe the issue when using PyCharm to setup the Conda environment is due to some sort of Python version conflict, but I might open another ticket for that. I'll close this ticket now.
